import 'dart:ui';
import 'package:path_drawing/path_drawing.dart';
import '../models/svg_document.dart';
import '../models/svg_node.dart';
import '../models/operation_type.dart';
import 'affine.dart';

class GcodeGenerator {
  static const double _step = 0.1; // mm per sample along curves

  static String generate(SvgDocument doc, String filename) {
    final buf = StringBuffer();
    final vb = doc.viewBox;

    buf
      ..writeln('; Generated by CNC Panel')
      ..writeln('; Source: $filename')
      ..writeln('; Work area: ${_f(vb.width)} x ${_f(vb.height)} mm')
      ..writeln('; Assumption: 1 SVG unit = 1 mm')
      ..writeln('; Y-axis: flipped (SVG Y-down → G-code Y-up)')
      ..writeln()
      ..writeln('G21 ; metric')
      ..writeln('G90 ; absolute positioning')
      ..writeln('M5 S0 ; laser off')
      ..writeln('G0 X0 Y0 ; move to origin')
      ..writeln();

    _walkNodes(doc.roots, SvgAffine.identity, vb, true, null, buf);

    buf
      ..writeln()
      ..writeln('G0 X0 Y0 ; return to origin')
      ..writeln('M5 S0 ; laser off')
      ..writeln('M2 ; end of program');

    return buf.toString();
  }

  static void _walkNodes(
    List<SvgNode> nodes,
    SvgAffine parentM,
    Rect vb,
    bool parentEnabled,
    OperationType? inheritedOp,
    StringBuffer buf,
  ) {
    for (final node in nodes) {
      if (!node.enabled || !parentEnabled) continue;

      final combined = parentM.multiply(SvgAffine.fromSvgString(node.transform));

      final ownOp = node.settings.operationType;
      final effectiveOp = ownOp != OperationType.skip ? ownOp : inheritedOp;

      if (node.pathData != null &&
          effectiveOp != null &&
          effectiveOp != OperationType.skip) {
        final s = node.settings;
        buf.writeln(
          '; --- ${node.label} [${effectiveOp.label}]'
          '  power:${s.powerPercent}%  speed:${s.speedMmMin} mm/min'
          '  passes:${s.passes} ---',
        );
        for (var pass = 0; pass < s.passes; pass++) {
          if (s.passes > 1) buf.writeln('; pass ${pass + 1}/${s.passes}');
          _pathToGcode(
              node.pathData!, combined, vb, s.powerPercent, s.speedMmMin, buf);
        }
      }

      _walkNodes(node.children, combined, vb, node.enabled, effectiveOp, buf);
    }
  }

  static void _pathToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int powerPct,
    int feedRate,
    StringBuffer buf,
  ) {
    final Path path;
    try {
      path = parseSvgPathData(pathData);
    } catch (_) {
      return;
    }
    final metrics = path.computeMetrics();
    final sPower = (powerPct * 10).clamp(0, 1000);
    int? lastF;

    for (final metric in metrics) {
      if (metric.length < 0.001) continue;

      // Sample points along contour
      final raw = <Offset>[];
      for (var d = 0.0; d <= metric.length; d += _step) {
        final t = metric.getTangentForOffset(d);
        if (t != null) raw.add(t.position);
      }
      // Always include endpoint
      final endT = metric.getTangentForOffset(metric.length);
      if (endT != null) raw.add(endT.position);
      if (raw.isEmpty) continue;

      // Transform + flip Y, then deduplicate
      final pts = <Offset>[];
      for (final p in raw) {
        final tp = xform.apply(p);
        final gp = Offset(tp.dx - vb.left, vb.bottom - tp.dy);
        if (pts.isEmpty || (gp - pts.last).distanceSquared > 1e-6) {
          pts.add(gp);
        }
      }
      if (pts.length < 2) continue;

      buf.writeln('M5 S0');
      buf.writeln('G0 X${_f(pts.first.dx)} Y${_f(pts.first.dy)}');
      buf.writeln('M3 S$sPower');

      for (var i = 1; i < pts.length; i++) {
        final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
        buf.writeln('G1 X${_f(pts[i].dx)} Y${_f(pts[i].dy)}$fTag');
        lastF = feedRate;
      }

      buf.writeln('M5 S0');
    }
  }

  /// Returns the SVG-space bounding rect of all enabled active-operation paths,
  /// or null when no active paths exist.
  static Rect? computeActiveBounds(SvgDocument doc) {
    Rect? bounds;
    void walk(List<SvgNode> nodes, bool pe, OperationType? iop, SvgAffine pm) {
      for (final n in nodes) {
        if (!n.enabled || !pe) continue;
        final m = pm.multiply(SvgAffine.fromSvgString(n.transform));
        final own = n.settings.operationType;
        final eff = own != OperationType.skip ? own : iop;
        if (n.pathData != null && eff != null && eff != OperationType.skip) {
          try {
            final path =
                parseSvgPathData(n.pathData!).transform(m.toFloat64());
            final b = path.getBounds();
            if (!b.isEmpty) {
              bounds = bounds == null ? b : bounds!.expandToInclude(b);
            }
          } catch (_) {}
        }
        walk(n.children, n.enabled, eff, m);
      }
    }

    walk(doc.roots, true, null, SvgAffine.identity);
    return bounds;
  }

  static String _f(double v) => v.toStringAsFixed(3);
}
