import 'dart:ui';
import 'package:path_drawing/path_drawing.dart';
import '../models/svg_document.dart';
import '../models/svg_node.dart';
import '../models/operation_type.dart';
import '../models/layer_settings.dart';
import '../models/machine_settings.dart';
import 'affine.dart';
import 'gcode_format.dart';
import 'path_offset.dart';
import 'svg_node_walker.dart';

class GcodeGenerator {
  static const double _step = 0.1; // mm per sample along curves

  static String generate(
    SvgDocument doc,
    String filename,
    MachineSettings settings,
  ) {
    final buf = StringBuffer();
    final vb = doc.viewBox;

    buf
      ..writeln('; Generated by EasyGRBL')
      ..writeln('; Source: $filename')
      ..writeln('; Work area: ${formatGcodeNumber(vb.width)} x ${formatGcodeNumber(vb.height)} mm')
      ..writeln('; Assumption: 1 SVG unit = 1 mm')
      ..writeln('; Y-axis: flipped (SVG Y-down → G-code Y-up)')
      ..writeln()
      ..writeln('G21 ; metric')
      ..writeln('G90 ; absolute positioning')
      ..writeln('M5 S0 ; laser off')
      ..writeln('G0 X0 Y0 Z0 ; HOME')
      ..writeln();

    walkSvgNodes(doc.roots, (node, transform, effectiveOp, effectiveSettings) {
      _writeNode(node, transform, vb, effectiveOp, effectiveSettings, settings, buf);
    });

    buf.writeln();
    if (settings.machineType == MachineType.mill) {
      final travelF = (settings.travelFeedRate * 60).round(); // mm/s -> mm/min
      buf
        ..writeln('G1 Z${formatGcodeNumber(settings.safeHeight)} F$travelF ; retract to safe height')
        ..writeln('G0 X0 Y0 ; XY HOME')
        ..writeln('G1 Z0 F$travelF ; Z HOME');
    } else {
      buf.writeln('G0 X0 Y0 Z0 ; HOME');
    }
    buf
      ..writeln('M5 S0 ; laser off')
      ..writeln('M2 ; end of program');

    return buf.toString();
  }

  static void _writeNode(
    SvgNode node,
    SvgAffine transform,
    Rect vb,
    OperationType? effectiveOp,
    LayerSettings effectiveSettings,
    MachineSettings settings,
    StringBuffer buf,
  ) {
    if (!isActiveOp(node.pathData, effectiveOp)) return;
    final op = effectiveOp!;
    final s = effectiveSettings;

    final feedRateMmMin = (s.speedMmS * 60).round(); // mm/s -> mm/min for F

    if (op == OperationType.fill) {
      final inset = s.fillOutline ? settings.laserSpotSize / 2 : 0.0;
      buf.writeln(
        '; --- ${node.label} [Fill]'
        '  power:${s.powerPercent}%  speed:${s.speedMmS.toStringAsFixed(1)} mm/s'
        '  lines/mm:${s.linesPerMm.toStringAsFixed(1)}'
        '  dir:${s.fillDirection.name}'
        '${s.fillOutline ? '  outline:yes  inset:${inset.toStringAsFixed(3)}mm' : ''} ---',
      );
      _fillToGcode(node.pathData!, transform, vb, s.powerPercent,
          feedRateMmMin, s.fillDirection, s.linesPerMm, settings, buf,
          inset: inset);
      if (s.fillOutline) {
        buf.writeln('; outline pass');
        _pathToGcode(node.pathData!, transform, vb, s.powerPercent,
            feedRateMmMin, settings, buf);
      }
    } else {
      final isCut = op == OperationType.cut;
      final offsetDelta = isCut ? settings.cutOffsetDeltaFor(s) : 0.0;
      final plungeZ = (isCut && settings.machineType == MachineType.mill)
          ? s.cutDepthMm
          : null;

      buf.writeln(
        '; --- ${node.label} [${op.label}]'
        '  power:${s.powerPercent}%  speed:${s.speedMmS.toStringAsFixed(1)} mm/s'
        '  passes:${s.passes}'
        '${offsetDelta != 0 ? '  side:${s.cutSide.name} offset:${offsetDelta.toStringAsFixed(3)}mm' : ''}'
        '${plungeZ != null ? '  Z:-${plungeZ.toStringAsFixed(3)}mm' : ''} ---',
      );
      for (var pass = 0; pass < s.passes; pass++) {
        if (s.passes > 1) buf.writeln('; pass ${pass + 1}/${s.passes}');
        _pathToGcode(node.pathData!, transform, vb, s.powerPercent,
            feedRateMmMin, settings, buf,
            offsetDeltaMm: offsetDelta, plungeZMm: plungeZ);
      }
    }
  }

  // ── Outline (engrave / cut) ────────────────────────────────────────────────

  static void _pathToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int powerPct,
    int feedRate,
    MachineSettings settings,
    StringBuffer buf, {
    double offsetDeltaMm = 0.0,
    double? plungeZMm,
  }) {
    final Path path;
    try {
      path = parseSvgPathData(pathData);
    } catch (_) {
      return;
    }
    final metrics = path.computeMetrics();
    final sMax = _sMaxFor(settings);
    final sPower = (powerPct / 100.0 * sMax).round().clamp(0, sMax);
    final travelF = (settings.travelFeedRate * 60).round(); // mm/s -> mm/min

    for (final metric in metrics) {
      if (metric.length < 0.001) continue;

      final raw = <Offset>[];
      for (var d = 0.0; d <= metric.length; d += _step) {
        final t = metric.getTangentForOffset(d);
        if (t != null) raw.add(t.position);
      }
      final endT = metric.getTangentForOffset(metric.length);
      if (endT != null) raw.add(endT.position);
      if (raw.isEmpty) continue;

      var pts = <Offset>[];
      for (final p in raw) {
        final tp = xform.apply(p);
        final gp = Offset(tp.dx - vb.left, vb.bottom - tp.dy);
        if (pts.isEmpty || (gp - pts.last).distanceSquared > 1e-6) {
          pts.add(gp);
        }
      }
      if (pts.length < 2) continue;

      if (offsetDeltaMm != 0) {
        pts = PathOffset.offsetClosedContour(pts, offsetDeltaMm);
      }

      buf.writeln('M5 S0');
      if (plungeZMm != null) {
        // Mill: rise to safe height before any horizontal travel, move to
        // the next cut position at that height, then plunge to depth.
        buf.writeln('G1 Z${formatGcodeNumber(settings.safeHeight)} F$travelF');
        buf.writeln('G1 X${formatGcodeNumber(pts.first.dx)} Y${formatGcodeNumber(pts.first.dy)} F$travelF');
        buf.writeln('${settings.laserMode.gcode} S$sPower');
        buf.writeln('G1 Z${formatGcodeNumber(-plungeZMm)} F$travelF');
      } else {
        buf.writeln('G0 X${formatGcodeNumber(pts.first.dx)} Y${formatGcodeNumber(pts.first.dy)}');
        buf.writeln('${settings.laserMode.gcode} S$sPower');
      }

      // lastF resets per contour: the travel/plunge moves above (Mill) leave
      // the machine's modal feed at travelF, so the first cutting move must
      // always re-assert feedRate rather than assume it's still active.
      int? lastF;
      for (var i = 1; i < pts.length; i++) {
        final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
        buf.writeln('G1 X${formatGcodeNumber(pts[i].dx)} Y${formatGcodeNumber(pts[i].dy)}$fTag');
        lastF = feedRate;
      }

      buf.writeln('M5 S0');
      if (plungeZMm != null) {
        buf.writeln('G1 Z${formatGcodeNumber(settings.safeHeight)} F$travelF');
      }
    }
  }

  // ── Fill (scanline hatch) ──────────────────────────────────────────────────

  static void _fillToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int powerPct,
    int feedRate,
    FillDirection direction,
    double linesPerMm,
    MachineSettings settings,
    StringBuffer buf, {
    double inset = 0.0,
  }) {
    final Path rawPath;
    try {
      rawPath = parseSvgPathData(pathData);
    } catch (_) {
      return;
    }

    // Apply transform in SVG space, then compute fill lines
    final path = rawPath.transform(xform.toFloat64());
    final lines = computeFillLines(path, direction, linesPerMm, inset: inset);
    if (lines.isEmpty) return;

    final sMax = _sMaxFor(settings);
    final sPower = (powerPct / 100.0 * sMax).round().clamp(0, sMax);
    int? lastF;

    for (final line in lines) {
      // Flip Y for G-code coordinate system
      final x1 = line.$1.dx - vb.left;
      final y1 = vb.bottom - line.$1.dy;
      final x2 = line.$2.dx - vb.left;
      final y2 = vb.bottom - line.$2.dy;

      buf.writeln('M5 S0');
      buf.writeln('G0 X${formatGcodeNumber(x1)} Y${formatGcodeNumber(y1)}');
      buf.writeln('${settings.laserMode.gcode} S$sPower');
      final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
      buf.writeln('G1 X${formatGcodeNumber(x2)} Y${formatGcodeNumber(y2)}$fTag');
      lastF = feedRate;
      buf.writeln('M5 S0');
    }
  }

  /// Computes fill line segments in SVG space using scanline intersection.
  /// Returns pairs (start, end) in alternating directions (boustrophedon).
  /// Handles compound paths (e.g. shapes with holes) correctly via even-odd rule.
  ///
  /// [inset] shrinks each line segment by this amount on both ends and narrows
  /// the scanline band accordingly — use spotSize/2 to avoid double-burning
  /// when an outline pass is also generated.
  static List<(Offset, Offset)> computeFillLines(
    Path path,
    FillDirection direction,
    double linesPerMm, {
    double inset = 0.0,
  }) {
    final bounds = path.getBounds();
    if (bounds.isEmpty) return const [];

    final step = 1.0 / linesPerMm;
    final result = <(Offset, Offset)>[];

    // Build one closed polygon per contour — do NOT connect contours to each
    // other.  A naïve single boundary list would create spurious segments
    // between subpaths (e.g. the closing point of an outer circle joined to
    // the first point of the inner hole), producing wrong crossings and
    // filling areas that should remain empty.
    final contours = <List<Offset>>[];
    for (final metric in path.computeMetrics()) {
      if (metric.length < 0.001) continue;
      final pts = <Offset>[];
      final start = metric.getTangentForOffset(0)?.position;
      var d = 0.0;
      while (d <= metric.length) {
        final t = metric.getTangentForOffset(d);
        if (t != null) pts.add(t.position);
        d += _step;
      }
      if (start != null) pts.add(start); // close back to start
      if (pts.length >= 2) contours.add(pts);
    }
    if (contours.isEmpty) return const [];

    if (direction == FillDirection.horizontal) {
      var leftToRight = true;
      var y = bounds.top + inset.clamp(0, double.infinity);
      if (y < bounds.top + step * 0.5) y = bounds.top + step * 0.5;
      while (y < bounds.bottom - inset) {
        final xs = _crossingsX(contours, y);
        for (var i = 0; i + 1 < xs.length; i += 2) {
          final a = xs[i] + inset;
          final b = xs[i + 1] - inset;
          if (a >= b) continue;
          result.add(leftToRight
              ? (Offset(a, y), Offset(b, y))
              : (Offset(b, y), Offset(a, y)));
          leftToRight = !leftToRight;
        }
        y += step;
      }
    } else {
      var topToBottom = true;
      var x = bounds.left + inset.clamp(0, double.infinity);
      if (x < bounds.left + step * 0.5) x = bounds.left + step * 0.5;
      while (x < bounds.right - inset) {
        final ys = _crossingsY(contours, x);
        for (var i = 0; i + 1 < ys.length; i += 2) {
          final a = ys[i] + inset;
          final b = ys[i + 1] - inset;
          if (a >= b) continue;
          result.add(topToBottom
              ? (Offset(x, a), Offset(x, b))
              : (Offset(x, b), Offset(x, a)));
          topToBottom = !topToBottom;
        }
        x += step;
      }
    }

    return result;
  }

  /// Finds all X intersections of a horizontal scanline at [y] with [contours].
  static List<double> _crossingsX(List<List<Offset>> contours, double y) {
    final xs = <double>[];
    for (final boundary in contours) {
      for (var i = 0; i < boundary.length - 1; i++) {
        final p1 = boundary[i], p2 = boundary[i + 1];
        if ((p1.dy <= y && p2.dy > y) || (p2.dy <= y && p1.dy > y)) {
          final t = (y - p1.dy) / (p2.dy - p1.dy);
          xs.add(p1.dx + t * (p2.dx - p1.dx));
        }
      }
    }
    xs.sort();
    return xs;
  }

  /// Finds all Y intersections of a vertical scanline at [x] with [contours].
  static List<double> _crossingsY(List<List<Offset>> contours, double x) {
    final ys = <double>[];
    for (final boundary in contours) {
      for (var i = 0; i < boundary.length - 1; i++) {
        final p1 = boundary[i], p2 = boundary[i + 1];
        if ((p1.dx <= x && p2.dx > x) || (p2.dx <= x && p1.dx > x)) {
          final t = (x - p1.dx) / (p2.dx - p1.dx);
          ys.add(p1.dy + t * (p2.dy - p1.dy));
        }
      }
    }
    ys.sort();
    return ys;
  }

  // ── Bounds (used by framing / job preview) ─────────────────────────────────

  /// Returns the SVG-space bounding rect of all enabled active-operation paths,
  /// or null when no active paths exist.
  static Rect? computeActiveBounds(SvgDocument doc) {
    Rect? bounds;
    walkSvgNodes(doc.roots, (node, transform, effectiveOp, effectiveSettings) {
      if (!isActiveOp(node.pathData, effectiveOp)) return;
      try {
        final path =
            parseSvgPathData(node.pathData!).transform(transform.toFloat64());
        final b = path.getBounds();
        if (!b.isEmpty) {
          bounds = bounds == null ? b : bounds!.expandToInclude(b);
        }
      } catch (_) {}
    });
    return bounds;
  }

  /// S-value ceiling for `M3/M4 S<value>`: the laser's $30 max power (sMax)
  /// for Laser, or the spindle's max RPM for Mill — so "Power %" in Layer
  /// Settings maps to a real spindle speed instead of a laser-only figure.
  static int _sMaxFor(MachineSettings settings) =>
      settings.machineType == MachineType.mill
          ? settings.maxSpindleSpeed
          : settings.sMax;
}
