import 'dart:ui';
import 'package:path_drawing/path_drawing.dart';
import '../../geometry/affine.dart';
import '../../geometry/contour_sampler.dart';
import '../../geometry/fill_lines.dart';
import '../../geometry/path_offset.dart';
import '../../geometry/svg_node_walker.dart';
import '../../models/layer_settings.dart';
import '../../models/operation_type.dart';
import '../../models/svg_document.dart';
import '../../models/svg_node.dart';
import '../../services/gcode_format.dart';
import '../machine_settings.dart';
import 'gcode_strategy.dart';

/// SVG → G-code. This is the mode-agnostic skeleton (header, SVG walk,
/// passes, sampling, Y flip, feed deduplication); everything that differs
/// between Laser and Mill is delegated to a [GcodeStrategy].
class GcodeGenerator {
  static const double _step = 0.1; // mm per sample along curves

  static String generate(
    SvgDocument doc,
    String filename,
    MachineSettings settings,
  ) {
    final strategy = GcodeStrategy.of(settings);
    final buf = StringBuffer();
    final vb = doc.viewBox;

    buf
      ..writeln('; Generated by EasyGRBL')
      ..writeln('; Source: $filename')
      ..writeln('; Work area: ${formatGcodeNumber(vb.width)} x ${formatGcodeNumber(vb.height)} mm')
      ..writeln('; Assumption: 1 SVG unit = 1 mm')
      ..writeln('; Y-axis: flipped (SVG Y-down → G-code Y-up)')
      ..writeln()
      ..writeln('G21 ; metric')
      ..writeln('G90 ; absolute positioning')
      ..writeln('M5 S0 ; laser off')
      ..writeln('G0 X0 Y0 Z0 ; HOME')
      ..writeln();

    walkSvgNodes(doc.roots, (node, transform, effectiveOp, effectiveSettings) {
      _writeNode(node, transform, vb, effectiveOp, effectiveSettings, strategy, buf);
    });

    buf.writeln();
    strategy.writeFooterMoves(buf);
    buf
      ..writeln('M5 S0 ; laser off')
      ..writeln('M2 ; end of program');

    return buf.toString();
  }

  static void _writeNode(
    SvgNode node,
    SvgAffine transform,
    Rect vb,
    OperationType? effectiveOp,
    LayerSettings effectiveSettings,
    GcodeStrategy strategy,
    StringBuffer buf,
  ) {
    if (!isActiveOp(node.pathData, effectiveOp)) return;
    final op = effectiveOp!;
    final s = effectiveSettings;

    final feedRateMmMin = (s.speedMmS * 60).round(); // mm/s -> mm/min for F
    final sMax = strategy.sMax;
    final sPower = (s.powerPercent / 100.0 * sMax).round().clamp(0, sMax);

    if (op == OperationType.fill) {
      final inset = strategy.fillInset(s);
      buf.writeln(
        '; --- ${node.label} [Fill]'
        '  power:${s.powerPercent}%  speed:${s.speedMmS.toStringAsFixed(1)} mm/s'
        '  lines/mm:${s.linesPerMm.toStringAsFixed(1)}'
        '  dir:${s.fillDirection.name}'
        '${s.fillOutline ? '  outline:yes  inset:${inset.toStringAsFixed(3)}mm' : ''} ---',
      );
      _fillToGcode(node.pathData!, transform, vb, sPower, feedRateMmMin,
          s.fillDirection, s.linesPerMm, strategy, buf,
          inset: inset);
      if (s.fillOutline) {
        buf.writeln('; outline pass');
        _pathToGcode(
            node.pathData!, transform, vb, sPower, feedRateMmMin, strategy, buf);
      }
    } else {
      final isCut = op == OperationType.cut;
      final offsetDelta = isCut ? strategy.cutOffsetDelta(s) : 0.0;
      final plungeZ = strategy.plungeDepth(op, s);

      buf.writeln(
        '; --- ${node.label} [${op.label}]'
        '  power:${s.powerPercent}%  speed:${s.speedMmS.toStringAsFixed(1)} mm/s'
        '  passes:${s.passes}'
        '${offsetDelta != 0 ? '  side:${s.cutSide.name} offset:${offsetDelta.toStringAsFixed(3)}mm' : ''}'
        '${plungeZ != null ? '  Z:-${plungeZ.toStringAsFixed(3)}mm' : ''} ---',
      );
      for (var pass = 0; pass < s.passes; pass++) {
        if (s.passes > 1) buf.writeln('; pass ${pass + 1}/${s.passes}');
        _pathToGcode(
            node.pathData!, transform, vb, sPower, feedRateMmMin, strategy, buf,
            offsetDeltaMm: offsetDelta, plungeZMm: plungeZ);
      }
    }
  }

  // ── Outline (engrave / cut) ────────────────────────────────────────────────

  static void _pathToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int sPower,
    int feedRate,
    GcodeStrategy strategy,
    StringBuffer buf, {
    double offsetDeltaMm = 0.0,
    double? plungeZMm,
  }) {
    final contours = sampleContours(pathData, step: _step, minDistSq: 1e-6,
        map: (p) {
      final tp = xform.apply(p);
      return Offset(tp.dx - vb.left, vb.bottom - tp.dy);
    });

    for (var pts in contours) {
      if (offsetDeltaMm != 0) {
        pts = PathOffset.offsetClosedContour(pts, offsetDeltaMm);
      }

      buf.writeln('M5 S0');
      strategy.writeContourStart(buf, pts.first, sPower, plungeZMm);

      // lastF resets per contour: the travel/plunge moves above (Mill) leave
      // the machine's modal feed at the travel feed, so the first cutting move
      // must always re-assert feedRate rather than assume it's still active.
      int? lastF;
      for (var i = 1; i < pts.length; i++) {
        final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
        buf.writeln('G1 X${formatGcodeNumber(pts[i].dx)} Y${formatGcodeNumber(pts[i].dy)}$fTag');
        lastF = feedRate;
      }

      buf.writeln('M5 S0');
      strategy.writeContourEnd(buf, plungeZMm);
    }
  }

  // ── Fill (scanline hatch) ──────────────────────────────────────────────────

  static void _fillToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int sPower,
    int feedRate,
    FillDirection direction,
    double linesPerMm,
    GcodeStrategy strategy,
    StringBuffer buf, {
    double inset = 0.0,
  }) {
    final Path rawPath;
    try {
      rawPath = parseSvgPathData(pathData);
    } catch (_) {
      return;
    }

    // Apply transform in SVG space, then compute fill lines
    final path = rawPath.transform(xform.toFloat64());
    final lines = computeFillLines(path, direction, linesPerMm, inset: inset);
    if (lines.isEmpty) return;

    int? lastF;
    for (final line in lines) {
      // Flip Y for G-code coordinate system
      final x1 = line.$1.dx - vb.left;
      final y1 = vb.bottom - line.$1.dy;
      final x2 = line.$2.dx - vb.left;
      final y2 = vb.bottom - line.$2.dy;

      buf.writeln('M5 S0');
      buf.writeln('G0 X${formatGcodeNumber(x1)} Y${formatGcodeNumber(y1)}');
      buf.writeln('${strategy.spindleOnCode} S$sPower');
      final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
      buf.writeln('G1 X${formatGcodeNumber(x2)} Y${formatGcodeNumber(y2)}$fTag');
      lastF = feedRate;
      buf.writeln('M5 S0');
    }
  }
}
