import 'dart:ui';
import 'package:path_drawing/path_drawing.dart';
import '../../geometry/affine.dart';
import '../../geometry/contour_sampler.dart';
import '../../geometry/fill_toolpath.dart';
import '../../geometry/path_offset.dart';
import '../../geometry/svg_node_walker.dart';
import '../../models/layer_settings.dart';
import '../../models/operation_type.dart';
import '../../models/svg_document.dart';
import '../../models/svg_node.dart';
import '../../services/gcode_format.dart';
import '../machine_settings.dart';
import 'gcode_strategy.dart';

/// SVG → G-code. This is the mode-agnostic skeleton (header, SVG walk,
/// passes, sampling, Y flip, feed deduplication); everything that differs
/// between Laser and Mill is delegated to a [GcodeStrategy].
class GcodeGenerator {
  static const double _step = 0.1; // mm per sample along curves

  static String generate(
    SvgDocument doc,
    String filename,
    MachineSettings settings,
  ) {
    final strategy = GcodeStrategy.of(settings);
    final buf = StringBuffer();
    final vb = doc.viewBox;

    buf
      ..writeln('; Generated by EasyGRBL')
      ..writeln('; Source: $filename')
      ..writeln('; Work area: ${formatGcodeNumber(vb.width)} x ${formatGcodeNumber(vb.height)} mm')
      ..writeln('; Assumption: 1 SVG unit = 1 mm')
      ..writeln('; Y-axis: flipped (SVG Y-down → G-code Y-up)')
      ..writeln()
      ..writeln('G21 ; metric')
      ..writeln('G90 ; absolute positioning')
      ..writeln('M5 S0 ; laser off')
      ..writeln('G0 X0 Y0 Z0 ; HOME')
      ..writeln();

    walkSvgNodes(doc.roots, (node, transform, effectiveOp, effectiveSettings) {
      _writeNode(node, transform, vb, effectiveOp, effectiveSettings, strategy, buf);
    });

    buf.writeln();
    strategy.writeFooterMoves(buf);
    buf
      ..writeln('M5 S0 ; laser off')
      ..writeln('M2 ; end of program');

    return buf.toString();
  }

  static void _writeNode(
    SvgNode node,
    SvgAffine transform,
    Rect vb,
    OperationType? effectiveOp,
    LayerSettings effectiveSettings,
    GcodeStrategy strategy,
    StringBuffer buf,
  ) {
    if (!isActiveOp(node.pathData, effectiveOp)) return;
    final op = effectiveOp!;
    final s = effectiveSettings;

    final feedRateMmMin = (s.speedMmS * 60).round(); // mm/s -> mm/min for F
    final sMax = strategy.sMax;
    final sPower = (s.powerPercent / 100.0 * sMax).round().clamp(0, sMax);

    if (op == OperationType.fill) {
      buf.writeln(
        '; --- ${node.label} [Fill]'
        '  power:${s.powerPercent}%  speed:${s.speedMmS.toStringAsFixed(1)} mm/s'
        '  lines/mm:${s.linesPerMm.toStringAsFixed(1)}'
        '  dir:${s.fillDirection.name}'
        '  inset:${(strategy.fillSpotDiameter / 2).toStringAsFixed(3)}mm'
        '${s.fillOutline ? '  outline:yes' : ''} ---',
      );
      _fillToGcode(node.pathData!, transform, vb, sPower, feedRateMmMin, s,
          strategy, buf);
    } else {
      final isCut = op == OperationType.cut;
      final offsetDelta = isCut ? strategy.cutOffsetDelta(s) : 0.0;
      final plungeZ = strategy.plungeDepth(op, s);

      buf.writeln(
        '; --- ${node.label} [${op.label}]'
        '  power:${s.powerPercent}%  speed:${s.speedMmS.toStringAsFixed(1)} mm/s'
        '  passes:${s.passes}'
        '${offsetDelta != 0 ? '  side:${s.cutSide.name} offset:${offsetDelta.toStringAsFixed(3)}mm' : ''}'
        '${plungeZ != null ? '  Z:-${plungeZ.toStringAsFixed(3)}mm' : ''} ---',
      );
      for (var pass = 0; pass < s.passes; pass++) {
        if (s.passes > 1) buf.writeln('; pass ${pass + 1}/${s.passes}');
        _pathToGcode(
            node.pathData!, transform, vb, sPower, feedRateMmMin, strategy, buf,
            offsetDeltaMm: offsetDelta, plungeZMm: plungeZ);
      }
    }
  }

  // ── Outline (engrave / cut) ────────────────────────────────────────────────

  static void _pathToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int sPower,
    int feedRate,
    GcodeStrategy strategy,
    StringBuffer buf, {
    double offsetDeltaMm = 0.0,
    double? plungeZMm,
  }) {
    final contours = sampleContours(pathData, step: _step, minDistSq: 1e-6,
        map: (p) {
      final tp = xform.apply(p);
      return Offset(tp.dx - vb.left, vb.bottom - tp.dy);
    });
    _contoursToGcode(
        [
          for (final pts in contours)
            offsetDeltaMm != 0
                ? PathOffset.offsetClosedContour(pts, offsetDeltaMm)
                : pts,
        ],
        sPower, feedRate, strategy, buf,
        plungeZMm: plungeZMm);
  }

  /// Burns each of [contours] (machine coordinates) as one tool-on run.
  static void _contoursToGcode(
    List<List<Offset>> contours,
    int sPower,
    int feedRate,
    GcodeStrategy strategy,
    StringBuffer buf, {
    double? plungeZMm,
  }) {
    for (final pts in contours) {
      buf.writeln('M5 S0');
      strategy.writeContourStart(buf, pts.first, sPower, plungeZMm);

      // lastF resets per contour: the travel/plunge moves above (Mill) leave
      // the machine's modal feed at the travel feed, so the first cutting move
      // must always re-assert feedRate rather than assume it's still active.
      int? lastF;
      for (var i = 1; i < pts.length; i++) {
        final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
        buf.writeln('G1 X${formatGcodeNumber(pts[i].dx)} Y${formatGcodeNumber(pts[i].dy)}$fTag');
        lastF = feedRate;
      }

      buf.writeln('M5 S0');
      strategy.writeContourEnd(buf, plungeZMm);
    }
  }

  // ── Fill (scanline hatch + optional outline) ───────────────────────────────

  static void _fillToGcode(
    String pathData,
    SvgAffine xform,
    Rect vb,
    int sPower,
    int feedRate,
    LayerSettings s,
    GcodeStrategy strategy,
    StringBuffer buf,
  ) {
    final Path rawPath;
    try {
      rawPath = parseSvgPathData(pathData);
    } catch (_) {
      return;
    }

    // Compute in SVG space, then flip Y for the G-code coordinate system.
    final fill = computeFillToolpath(rawPath.transform(xform.toFloat64()),
        direction: s.fillDirection,
        linesPerMm: s.linesPerMm,
        spotDiameter: strategy.fillSpotDiameter,
        outline: s.fillOutline);
    Offset toMachine(Offset p) => Offset(p.dx - vb.left, vb.bottom - p.dy);

    int? lastF;
    for (final line in fill.lines) {
      final a = toMachine(line.$1);
      final b = toMachine(line.$2);

      buf.writeln('M5 S0');
      buf.writeln('G0 X${formatGcodeNumber(a.dx)} Y${formatGcodeNumber(a.dy)}');
      buf.writeln('${strategy.spindleOnCode} S$sPower');
      final fTag = (lastF == feedRate) ? '' : ' F$feedRate';
      buf.writeln('G1 X${formatGcodeNumber(b.dx)} Y${formatGcodeNumber(b.dy)}$fTag');
      lastF = feedRate;
      buf.writeln('M5 S0');
    }

    if (fill.outline.isEmpty) return;
    buf.writeln('; outline pass');
    _contoursToGcode(
        [for (final c in fill.outline) c.map(toMachine).toList()],
        sPower, feedRate, strategy, buf);
  }
}
